targets:
  $default:
    builders:
      copyable_generator|copyable:
        generate_for:
          - lib/rectangle.dart
      copyable_generator|copier:
        generate_for:
          - lib/circle.dart
      copyable_generator|foreignCopyableLib:
        generate_for:
          - lib/metas.dart
      copyable_generator|foreignCopierLib:
        generate_for:
          - lib/metas.dart