targets:
  $default:
    builders:
      copyable_generator|copyable:
        generate_for:
          - lib/copyable_example.dart
      copyable_generator|foreignCopyable:
        generate_for:
          - lib/copyable_example.dart
      copyable_generator|copier:
        generate_for:
          - lib/copier_example.dart
      copyable_generator|foreignCopier:
        generate_for:
          - lib/copier_example.dart