targets:
  $default:
    builders:
      copyable|copyable:
        generate_for:
          - lib/rectangle.dart
      copyable|copier:
        generate_for:
          - lib/circle.dart
      copyable|foreignCopyableLib:
        generate_for:
          - lib/metas.dart
      copyable|foreignCopierLib:
        generate_for:
          - lib/metas.dart