targets:
  $default:
    builders:
      copyable_generator|copyable:
        generate_for:
          - lib/copyable_example.dart
      copyable_generator|copier:
        generate_for:
          - lib/copier_example.dart
      copyable_generator|foreignCopyableLib:
        generate_for:
          - lib/metas_example.dart
      copyable_generator|foreignCopierLib:
        generate_for:
          - lib/metas_example.dart