builders:
  copier:
    import: "package:copyable_generator/builder.dart"
    builder_factories: ["copierBuilder"]
    build_extensions: {".dart": ["copier.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  copyable:
    import: "package:copyable_generator/builder.dart"
    builder_factories: ["copyableBuilder"]
    build_extensions: {".dart": [".copyable.dart"]}
    auto_apply: dependents
    build_to: source

  functions:
    import: "package:copyable_generator/builder.dart"
    builder_factories: ["copyFunctionsBuilder"]
    build_extensions: {".dart": ["functions.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  foreignCopier:
    import: "package:copyable_generator/builder.dart"
    builder_factories: ["foreignCopierBuilder"]
    build_extensions: {".dart": [".copier.dart"]}
    auto_apply: dependents
    build_to: source
